### PR TITLE
added animation to feature block linked images

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Add zoom animation to Feature Blocks and Film Cards for Double Film Strip

# Needed By (Date)
- N/A

# Urgency
- No

# Steps to Test

1. Pull this branch
2. Test zoom and overflow for Feature Blocks on /patterns page

# Affected Projects or Products
- Earth
- stanford_components

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/EARTH-399

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
During the zoom, the gradiant goes away. is that a desired effect?

**Comment by josephgknox** [comment]
@pookmish good catch on the Feature Blocks. I agree that the animation should be added to those as well.

Regarding the gradient: I'm open to either; there is not pattern for this yet. I've reviewed this with Nick as currently implemented and got his verbal sign off.

**Comment by josephgknox** [comment]
@pookmish here you go!

**Comment by pookmish** [comment]
That works better. now i have a question about implementation. I'm not sure i have a strong opinion either way, so maybe @sherakama can be a deciding voice. Should the animation live in `simple_block` vs `feature_blocks`. Then it would be used in more patterns. Similarly to the double filmstrip. If we move the animation to filmcard it would be applied to double filmstrip, tall filmstrip etc. 
I'm unsure if this is desired though.

**Comment by josephgknox** [comment]
@pookmish @sherakama upon thinking about this more, and combing through the patterns page, I do think we want this to live in simple_block for consistency.

Change has been made.

**Pull request merged**
