### PR TITLE
Earth 13 tackle

### PR DESCRIPTION
**Pull request by koppieesq**
**This is still in progress.**

Creating a PR for Shea to help out.  Will circle back on Tuesday.

### CODE REVIEW

**Comment by koppieesq** [comment]
Looks like I forked this from EARTH-12 instead of 8.x-1.x.  Sorry about that!

**Comment by sherakama** [comment]
Also, this PR is dependant on https://github.com/SU-SWS/stanford_components/pull/1 and cannot be merged until that one has been merged unless you remove the HERO-12 commits.

Thanks.

**Comment by koppieesq** [comment]
@sherakama you got it working, thanks!!!

I'll finish up the css & whatever else needs to be done.  Three questions:
1. I'm wondering if it would be better to include the film_card library in the fimlstrip yaml file instead of the twig file?
2. For the film_card, I'm still not able to include styling from film-card.theme.scss.  Any thoughts?
3. Good point re. dependency on HERO-12.  That was not intentional - I accidentally forked from my feature branch rather than from the 8.x branch.  Should I cherry pick and remove the dependencies on HERO-12?

**Comment by sherakama** [comment]
@koppieesq,

1. I think having the attach library in the twig file makes sense. This was if the film strip gets included by an organism in the future the developer won't have to also figure out which library to include. Also, it seems less brittle than including the css files of the film-card library in the film-strip library. I am open to suggestions otherwise.

2. Not sure why you arn't seeing the theme.css changes. The stylesheet is loading for me. Ensure that your branch is up to date and all the caches have been cleared.

3. I can work around the branched from EARTH-12 stuff. Please ensure you start your future work off the main branch as it makes it much much easier to review and merge.

**Comment by koppieesq** [comment]
I've uploaded a polished draft.  I'm going to review the Code Climate report and re-upload this afternoon.

**Comment by koppieesq** [comment]
@sherakama this is ready for your review.  We have two molecules: one for an individual film-card, and another for the filmstrip.  Code Climate is complaining about my use of !important but that's it.  I agree that !important should be avoided whenever possible, but in this case there are issues with css inheritance & precedence because we're reusing an existing mixin.  This is an exception to the rule.

Other than that, I've fixed all the typos identified by Code Climate, and tested across all desktop browsers, and also made it responsive.  I believe this meets the definition of done.  😄

**Comment by koppieesq** [comment]
# READY FOR REVIEW

# Summary
"Challenges we tackle" strip of small cards on home page.

This is actually a _molecule inside a molecule_: We now have both individual film-cards and a filmstrip that is made up of film-cards with a wrapper and title.

# Needed By (Date)
No specific timeline for this feature

# Steps to Test

1. Create a new "filmstrip" type object (paragraph, block, whatever)
2. Add the thing to a page
3. Populate the fields (eg. title)

# Affected versions or modules
- stanford_components

# Associated Issues and/or People
- JIRA ticket EARTH-13
- See also EARTH-81 for an exploration of how to put this in a View
- Relies on #1 because I accidentally forked from that branch
- Anyone who should be notified? @sherakama 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

**Comment by sherakama** [comment]
Merged on the command line here: https://github.com/SU-SWS/stanford_components/commit/f7dd24680b955a8b9a0ebb9c34f526328ebd981a

**Comment by koppieesq** [comment]
Just for the sake of cleanliness, @sherakama can we delete this branch?

**Comment by sherakama** [comment]
I left it open in case we wanted to review it later. Should be good to go now. I'll delete.

**Pull request closed without merging**
